export interface KnowledgeSnippet {
  id: string;
  title: string;
  text: string;
}

/**
 * A small illustrative knowledge base the AI features retrieve from before
 * answering. General-education paraphrases, not official IRS guidance or tax
 * advice — good enough to demo grounded retrieval, not a substitute for a
 * CPA. This is the "document corpus" side of the RAG pipeline in
 * src/lib/retrieval.ts.
 */
export const taxKnowledge: KnowledgeSnippet[] = [
  { id: 'w2-box1', title: 'W-2 Box 1 — Wages, tips, other compensation', text: 'Box 1 on a W-2 shows your total taxable wages for the year — your salary or hourly pay plus bonuses and tips, minus things like pre-tax 401(k) contributions and health insurance premiums. It is usually lower than your gross salary.' },
  { id: 'w2-box2', title: 'W-2 Box 2 — Federal income tax withheld', text: 'Box 2 is the total federal income tax your employer already sent to the IRS on your behalf throughout the year. This amount is credited against what you actually owe when your return is filed.' },
  { id: '1099-nec', title: '1099-NEC — Nonemployee compensation', text: 'A 1099-NEC reports payments of $600 or more made to an independent contractor or freelancer. Unlike W-2 wages, no tax is withheld from this income, so the recipient is generally responsible for estimated taxes and self-employment tax.' },
  { id: '1099-int', title: '1099-INT — Interest income', text: 'A 1099-INT reports interest earned from a bank account, CD, or bond. Even small amounts of interest are technically taxable income and should be reported on the return.' },
  { id: '1099-div', title: '1099-DIV — Dividend income', text: 'A 1099-DIV reports dividends paid by stocks or funds you own. Qualified dividends are usually taxed at a lower rate than ordinary income, while non-qualified (ordinary) dividends are taxed at your regular rate.' },
  { id: 'schedule-c', title: 'Schedule C — Profit or loss from business', text: 'Schedule C is used to report income and expenses for a sole proprietorship or single-member LLC. Gross receipts minus deductible business expenses produces the net profit that flows to the main return and is also subject to self-employment tax.' },
  { id: 'schedule-e', title: 'Schedule E — Supplemental income', text: 'Schedule E reports income or loss from rental real estate, royalties, partnerships, S corporations, and trusts — including K-1 income. It is a "pass-through" schedule: the entity itself usually does not pay tax, the owner does.' },
  { id: 'k1', title: 'Schedule K-1', text: 'A K-1 reports your share of income, deductions, and credits from a partnership, S corporation, or trust you have an ownership stake in. The entity files its own return, then issues K-1s to each owner to report on their personal return.' },
  { id: 'standard-vs-itemized', title: 'Standard vs. itemized deduction', text: 'Every filer can take a flat standard deduction, or itemize specific expenses (mortgage interest, state/local taxes up to a cap, charitable donations, large medical expenses) if that total is larger. Most filers come out ahead taking the standard deduction.' },
  { id: 'filing-status', title: 'Filing status', text: 'Filing status (single, married filing jointly, married filing separately, head of household, qualifying surviving spouse) affects your standard deduction, tax bracket thresholds, and eligibility for certain credits. It is generally based on your marital and household status on the last day of the tax year.' },
  { id: 'dependents', title: 'Claiming a dependent', text: 'A dependent is typically a qualifying child or relative you financially support who meets residency, age, and support tests. Claiming a dependent can unlock credits like the Child Tax Credit and a more favorable filing status.' },
  { id: 'home-office', title: 'Home office deduction', text: 'If part of your home is used regularly and exclusively for business, you may be able to deduct a portion of rent, utilities, and insurance proportional to that space, using either the simplified square-footage method or actual-expense method.' },
  { id: 'estimated-taxes', title: 'Estimated quarterly taxes', text: 'If you have income with no withholding — like 1099 or business income — you are generally expected to pay estimated taxes quarterly rather than in one lump sum, to avoid an underpayment penalty.' },
  { id: 'extension', title: 'Filing an extension', text: 'An extension gives you more time to file your paperwork, typically six extra months, but it does not extend the deadline to pay any tax owed — that is still due on the original date to avoid interest and penalties.' },
  { id: 'capital-gains', title: 'Capital gains', text: 'Selling an investment or property for more than you paid creates a capital gain. Assets held over a year usually qualify for lower long-term capital gains rates; assets held a year or less are taxed as short-term gains at ordinary income rates.' },
  { id: 'tax-brackets', title: 'How tax brackets work', text: 'The U.S. uses a marginal, progressive bracket system — only the portion of income that falls within a given bracket is taxed at that bracket\'s rate, not your entire income. Moving into a higher bracket does not reduce your take-home pay on the income below that threshold.' },
  { id: 'withholding', title: 'Refund vs. balance due', text: 'A refund means you paid more in withholding or estimated payments during the year than you actually owed; a balance due means you paid less than you owed. Neither is inherently good or bad — it just reflects how closely withholding matched actual tax liability.' },
  { id: 'self-employment-tax', title: 'Self-employment tax', text: 'Self-employment tax covers the Social Security and Medicare contributions that an employer would normally split with you. It applies to net self-employment income in addition to regular income tax, which is why freelance income is taxed at a noticeably different effective rate than W-2 wages.' },
  { id: 'amended-return', title: 'Amending a filed return', text: 'If you discover an error after filing — a missed form, wrong filing status, forgotten income — you can file an amended return to correct it. This does not usually trigger extra scrutiny by itself; it is a normal, routine correction process.' },
  { id: 'credits-vs-deductions', title: 'Tax credits vs. deductions', text: 'A deduction reduces the amount of income that is taxed; a credit reduces the tax bill itself, dollar for dollar. A $1,000 credit is generally worth more than a $1,000 deduction.' },
  { id: 'audit-risk', title: 'What increases audit risk', text: 'Common audit triggers include large deductions relative to income, cash-heavy businesses, math errors, unreported income that does not match a 1099/W-2 already on file with the IRS, and unusually round expense numbers that suggest estimation rather than recordkeeping.' },
  { id: 'recordkeeping', title: 'Recordkeeping for deductions', text: 'Claimed business expenses should be backed by receipts, bank/credit card statements, or invoices — not just a remembered total. Good recordkeeping is what turns a deduction from "plausible" into "defensible" if it is ever questioned.' },
  { id: 'confidence-score', title: 'What a confidence score means on this platform', text: 'When a field on this platform shows a confidence score, it reflects how certain the extraction step was that it read the right value from the right place on a source document. Lower scores usually mean the source was harder to parse (handwriting, a scanned photo, or a value that had to be calculated from several transactions) and deserve a manual check before being marked verified.' },
  { id: 'verified-status', title: 'What "Verified" means on this platform', text: 'A field marked Verified has been confirmed by a preparer or reviewer, not just extracted by AI. Once verified, it locks to prevent accidental edits — to change it, someone has to explicitly unlock it, which keeps a clear record of who confirmed what.' },
  { id: 'reviewer-role', title: 'What a reviewer does', text: 'On this platform, a reviewer is a second preparer who checks a return before it goes to the client for signature — verifying calculations, resolving flagged or low-confidence fields, and catching anything the original preparer might have missed.' },
];
